# Site settings
title: Florian Mainguy
email: florian.mainguy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love food
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://florianmainguy.github.io" # the base hostname & protocol for your site
twitter_username: WouF1664
github_username:  florianmainguy

# Build settings
markdown: kramdown
highlighter: pygments